# Generated by Django 4.1.7 on 2023-03-29 15:02

from django.db import migrations, models
import magazin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('count', models.IntegerField()),
                ('about', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(upload_to=magazin.models.file_path)),
                ('file', models.FileField(upload_to=magazin.models.file_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('count', models.IntegerField()),
                ('about', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(upload_to=magazin.models.file_path)),
                ('file', models.FileField(upload_to=magazin.models.file_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vitamins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('count', models.IntegerField()),
                ('about', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(upload_to=magazin.models.file_path)),
                ('file', models.FileField(upload_to=magazin.models.file_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
