# Generated by Django 4.1.7 on 2023-03-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_remove_makeup_file_remove_toys_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='makeup',
            name='tags',
            field=models.ManyToManyField(to='magazin.tags'),
        ),
        migrations.AddField(
            model_name='toys',
            name='tags',
            field=models.ManyToManyField(to='magazin.tags'),
        ),
        migrations.AddField(
            model_name='vitamins',
            name='tags',
            field=models.ManyToManyField(to='magazin.tags'),
        ),
    ]
