# Generated by Django 4.1.7 on 2023-04-10 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_tags_makeup_tags_toys_tags_vitamins_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)])),
                ('address', models.CharField(max_length=255)),
                ('payment', models.CharField(choices=[('card', 'Картой'), ('money', 'Наличными')], max_length=5)),
                ('count', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='magazin.makeup')),
            ],
        ),
    ]
