# Generated by Django 4.1.7 on 2023-04-21 10:21

from django.db import migrations, models
import magazin.models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0005_category_product_remove_makeup_tags_remove_toys_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='exit', upload_to=magazin.models.file_path),
            preserve_default=False,
        ),
    ]
