# Generated by Django 4.1.7 on 2023-04-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0006_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
