# Generated by Django 4.1.7 on 2023-04-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0008_tags_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
