version: "3.10"

services:
  localhost:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=finishProject
      - POSTGRES_USER=django_app_user
      - POSTGRES_PASSWORD=gfhjkm1
    volumes:
       - /data/db/var/lib/postgresql/data


  finishProject:
    build: .
    image: finishproject:v0.1
    command: runserver 0.0.0.0:8000
    volumes:
      - "./static:/app/static:ro"
      - "./media:/app/media"
    ports:
      - "8080:8000"
    environment:
      - POSTGRES_DB=finishProject
      - POSTGRES_USER=test_django_app_user
      - POSTGRES_PASSWORD=gfhjkm1
    depends_on:
         - localhost


