version: "3.10"

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=finishProject
      - POSTGRES_USER=test_django_app_user
      - POSTGRES_PASSWORD=gfhjkm1
    volumes:
      - /data/db/var/lib/postgresql/data


  finishProject:
    build: .
    image: finishproject:v0.5
    volumes:
      - "./static:/app/static:ro"
      - "./media:/app/media"
    ports:
      - "8080:8000"
    environment:
      - POSTGRES_DB=finishProject
      - POSTGRES_USER=test_django_app_user
      - POSTGRES_PASSWORD=gfhjkm1
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
    depends_on:
         - postgres-db


